name:                hash
version:             0.1.0.0
github:              "tgujar/hash"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tgujar/hash#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring-trie >= 0.2.6
- parsec
- containers
- QuickCheck
- mtl
- bytestring >= 0.10
- utf8-string >= 1.0.2
- haskeline >= 0.8.2
- transformers >= 0.5.6.2

library:
  source-dirs: src
  dependencies:
  - bytestring-trie >= 0.2.6
  - mtl
  - bytestring >= 0.10
  - utf8-string >= 1.0.2
  - haskeline >= 0.8.2
  - transformers >= 0.5.6.2

executables:
  hash-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hash

tests:
  hash-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hash
